### PR TITLE
WIP: Mustang Beta Drop 2

### PR DESCRIPTION
**Pull request by patel-bhavin**
[Not ready for merge into develop]

creating this so that the CI pipeline can save my life! :) 

Note: merge with develop updates can be found in this branch

### CODE REVIEW

**Comment by P4T12ICK** [comment]
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Access LSASS Memory for Dump Creation :x:
- diskUsage: 122880
- runDuration: 3.587s
- scanCount: 5573

**Comment by P4T12ICK** [comment]
test

**Comment by P4T12ICK** [comment]
test

**Comment by P4T12ICK** [comment]
test

**Review by jzsplunk — APPROVED** [review]

**Pull request merged**
